### ISSUE TITLE
trakt-tv.py TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by douggutaby** [c99koder/personal-influxdb#10]
I cannot get data from trakt.tv since 2021-03-08, but I realised this few days ago :(
I got this error message:
Traceback (most recent call last):
  File "./trakt-tv.py", line 78, in <module>
    for item in Trakt['sync/history'].get(pagination=True, per_page=100, start_at=datetime(date.today().year, date.today().month, 1), extended='full'):
TypeError: 'NoneType' object is not iterable

I tried to recreate my json file. It didn't work but now after I restored the original (it was from december):
Traceback (most recent call last):
  File "./trakt-tv.py", line 76, in <module>
    Trakt.configuration.defaults.oauth.from_response(auth)
  File "/usr/local/lib/python3.7/site-packages/trakt/core/configuration.py", line 157, in from_response
    raise ValueError('Invalid "response" parameter provided to oauth.from_response()')
ValueError: Invalid "response" parameter provided to oauth.from_response()

I'm totally lost what happened. Can you help me?

**Comment by c99koder** [comment]
Sounds like your token has expired.  You'll have to delete `.trakt.json` and generate a new `TRAKT_OAUTH_CODE ` by logging in from your browser again

**Comment by douggutaby** [comment]
Thank you, that was it.
