### ISSUE TITLE
Unable to obtain flight data from FsHub (TypeError: 'NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by allebb** [c99koder/personal-influxdb#11]
Hi Sam!

I'm trying to ingest my flight data from FsHub into InfluxDB but am getting the following error when running the script (**fshub.py**):

> Got flights 100 from FsHub
> Traceback (most recent call last):
>   File "./fshub.py", line 143, in <module>
>     cursor = fetch(100,cursor)
>   File "./fshub.py", line 44, in fetch
>     if flight['departure']['icao'] != None and flight['arrival']['icao'] != None:
> TypeError: 'NoneType' object is not subscriptable

Have you seen this before?

My profile (if it helps) can be found here: https://fshub.io/pilot/2/profile

Thanks for developing this awesome connector!

**Comment by c99koder** [comment]
Looks like you had a flight that was missing the departure information. I've fixed the script to properly handle that case

**Comment by allebb** [comment]
Awesome - thanks Sam!!!

I'll re-download and test it again now :+1
