### ISSUE TITLE
steam not working

### ISSUE THREAD

**Issue by sahara101** [c99koder/personal-influxdb#28]
Sorry for new issue but you closed the old  one  and I cannot reopen.

I still cannot connect to steam:

2023-08-23 03:11:17,165 Starting new HTTPS connection (1): steamcommunity.com:443
2023-08-23 03:11:17,580 https://steamcommunity.com:443 "GET /id/76561197996904310/games/?tab=all HTTP/1.1" 200 4961
2023-08-23 03:11:17,592 Uncaught exception:
Traceback (most recent call last):
  File "/root/steam.py", line 85, in <module>
    recents = scrape_recents()
  File "/root/steam.py", line 79, in scrape_recents
    data = soup.find('script', string=re.compile('var rgGames = \[\{')).string
AttributeError: 'NoneType' object has no attribute 'string'

steamfinder is showing fine 

Trying https://steamcommunity.com/id/76561197996904310/games/?tab=all. gives me profile not found?

Sorry if I ask stupid questions. I want to have this deployed and can barely keep my eyes open :)

**Comment by c99koder** [comment]
You need to change your privacy settings so your profile and game library are public, otherwise the scraper can't read the data.

**Comment by sahara101** [comment]
It is...
profile state: public

**Comment by c99koder** [comment]
Open Steam, click your username, click Profile, click Edit Profile, and scroll down to "Custom URL". That's the username in the URL you should be using to fetch your profile.
![image](https://github.com/c99koder/personal-influxdb/assets/84647/9da7b8cf-e70f-4994-97af-4808955fb8f0)

**Comment by sahara101** [comment]
Ah..thanks. The link works, but now I get this:

2023-08-23 03:33:25,535 Uncaught exception:
Traceback (most recent call last):
  File "/root/steam.py", line 85, in <module>
    recents = scrape_recents()
  File "/root/steam.py", line 79, in scrape_recents
    data = soup.find('script', string=re.compile('var rgGames = \[\{')).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by c99koder** [comment]
Are you able to view your games list and play time in a private browsing / incognito window in your browser?  If not, check your privacy settings and make sure the game data is public.

![image](https://github.com/c99koder/personal-influxdb/assets/84647/5f98d726-d8c1-4f63-b882-cdba684e0d7d)

**Comment by c99koder** [comment]
It looks like Valve recently changed the layout of the profile pages, I'll update the script tomorrow.

**Comment by sahara101** [comment]
Thanks!
