### ISSUE TITLE
Gaming dashboard

### ISSUE THREAD

**Issue by sahara101** [c99koder/personal-influxdb#29]
Hi and sorry for new issue.

I have added psn, influx receives the data. Yet the gaming dashboard has no data at all. I assume this is the correct dashboard for it?

Example 

<img width="1639" alt="image" src="https://github.com/c99koder/personal-influxdb/assets/22507692/1e4b4353-e57b-4b7d-bb92-5be1c17921e6">

Thanks!

**Comment by c99koder** [comment]
It's a problem with your SQL query. You're trying to use the mean() function which is numeric, on columns that contain text.

Try this query instead:
```SQL
SELECT last("value") AS "duration" FROM "gaming"."autogen"."time" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:), "title", "platform" FILL(none)
```

![image](https://github.com/c99koder/personal-influxdb/assets/84647/bdd6c86d-aed9-45de-8972-bf23adfd6589)

**Comment by c99koder** [comment]
Here's a query for the achievements:

```SQL
SELECT last("description") AS "last_description", last("icon") AS "last_icon", last("name") AS "last_name" FROM "gaming"."autogen"."achievement" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:), "platform", "title" FILL(none)
```

**Comment by sahara101** [comment]
I am still doing smth wrong: 

<img width="1663" alt="image" src="https://github.com/c99koder/personal-influxdb/assets/22507692/b6d3ef50-b897-439e-af17-65426a7bfd80">


Also, shouldn't influxdb1 not show automatically the correct syntax, because if not how can the gaming grafana dashboard show them?

**Comment by c99koder** [comment]
Check your time filter at the top right of the window. If you have it set to something small like the past 5 minutes, then you're not going to see any data.

![image](https://github.com/c99koder/personal-influxdb/assets/84647/252fd562-a052-4e62-bc4f-629876dea1a2)

**Comment by c99koder** [comment]
The Steam API only provides data for the past 2 weeks, so you'll only see what you've played recently, not your entire library.  I'm not sure about PSN, it was contributed by @Findarato but it's probably the same answer for that script too.

The grafana dashboard works fine for me, so there's probably something configured wrong on your end.  There's not much more I can do to help you with that, you'll have to read the Grafana documentation and make sure everything is set up correctly, and maybe modify some of the queries to match your environment if required.

**Comment by sahara101** [comment]
Found the issue: 

datasource is working. 0 measurements found

Now to check why...

**Comment by sahara101** [comment]
Issue is not with the API timeframe. The last 4 played games are not in the list
