### ISSUE TITLE
psn missing data

### ISSUE THREAD

**Issue by sahara101** [c99koder/personal-influxdb#30]
Hello :)
Unfortunately the psn.py does not take all data. 

I also am not sure if it is an API max history issue as I have missing data between existing data and last data missing as well.

Could we check this somehow?
I have started the script several times, each time same data gets pulled.

Thanks!

**Comment by c99koder** [comment]
Your exophase profile doesn't show any play time for those games, so that's why they're being skipped.  You can notify Exophase admins about the issue here and they can look into fixing their PSN importer for those games: https://forums.exophase.com/threads/psn-new-games-no-time-counting.57736/

**Comment by sahara101** [comment]
Thanks! That makes sense. Also I have checked again and the olders game is from 2021. What I see as older dates in the recent achievement are actually replayed games after 2021. Now the question is, would it be possible to extend the api search frame to more years and also, would it be possible to differenciate between PS4/PS5 games?

Thanks!

**Comment by sahara101** [comment]
Here an anwer regarding the api:

https://forums.exophase.com/threads/api-limitations.60743/#post-276163
