### ISSUE TITLE
trakt missing data

### ISSUE THREAD

**Issue by sahara101** [c99koder/personal-influxdb#31]
Hello, 

I have tried trakt as well. It gets 16 watched episodes in 2 days. Seems it does not pull correctly.

Thanks

**Comment by c99koder** [comment]
The trakt script fetches data only for the current month, you can change the start date on line 67 of the script.  These scripts are designed to be run frequently from a cron job, so they fetch only recent data not your entire history.  If you want to import historical data then you will need to modify most of the scripts yourself.

**Comment by sahara101** [comment]
Look at the difference please

<img width="1716" alt="image" src="https://github.com/c99koder/personal-influxdb/assets/22507692/6fd19226-3778-4b3b-9e9e-23deefaa16e3">
vs
<img width="287" alt="image" src="https://github.com/c99koder/personal-influxdb/assets/22507692/b673c70b-abfc-4667-947e-7e5a6883f9bd">

**Comment by sahara101** [comment]
OK now I have much more data, but ex last month I am still missing much, as per my screenshots

**Comment by c99koder** [comment]
Running the script today won't import anything before September 1st, unless you change the start date as mentioned in my original reply.

**Comment by sahara101** [comment]
Yes, I have changed the start date. Here I also wrote on the trakt api.

Data is missing between available data

https://github.com/trakt/api-help/discussions/414

**Comment by sahara101** [comment]
Than you

or item.action == "scrobble": made all appear
