### ISSUE TITLE
Various Issues

### ISSUE THREAD

**Issue by shrippen** [c99koder/personal-influxdb#4]
Hello,

I'm having trouble using your scripts. I'm not sure if I have done something wrong or if the scripts are maybe outdated or something?

The steam script throws the following error:

`
File "D:\python influx\steam.py", line 79, in <module>
    for app in fetch_recents():
  File "D:\python influx\steam.py", line 55, in fetch_recents
    json = response.json()
  File "C:\Users\arian\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\arian\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\arian\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

The fitbit Script throws me this error, maybe because I didn't fill in FITBIT_ACCESS_TOKEN and FITBIT_INITIAL_CODE but honestly I just didn't find out how I could get these.

`Traceback (most recent call last):
  File "/chronos/scripts/fitbit-to-influx/fitbit-to-influx.py", line 223, in <module>
    response.raise_for_status();
  File "/chronos/scripts/fitbit-to-influx/.venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.fitbit.com/oauth2/token
`

**Comment by c99koder** [comment]
You need to make your Steam activity public in order to use the Steam script, as it doesn't perform any authentication to view private data.

To get your FITBIT_INITIAL_CODE, go to the Fitbit dev portal at https://dev.fitbit.com/apps, click on your app, and then click on the "OAuth 2.0 tutorial page" link.  Then choose "Authorization code flow" and click the link they generate for you. After you login / grant authorization, the initial code will be in the URL bar of your browser between `?code=` and `#_=_`.

**Comment by shrippen** [comment]
According to Steam my activity is public - here is my profile: https://steamcommunity.com/id/Shrippen/

I have only set the Friends List, Inventory and "Can post comments on my profile" to Friends only.

**Comment by c99koder** [comment]
Just to confirm, you registered for an API key and entered your API key, SteamID (yours is `76561197971861258`), and your username into the variables at the top of the script?  It works fine for me when I run it with my API key and your SteamID

**Comment by shrippen** [comment]
Ah now there was the problem. I thought my SteamID is my Steam Account. My mistake.

Thanks for the scripts btw. This morning I had this idea "shouldn't it be possible to log "normal" stuff to influx" and bam you already made some wonderful scripts. Much obliged.

**Comment by c99koder** [comment]
I've added a note to the README to make it a bit more clear that you need to use your SteamID and not your username. Let me know if you have any other issues!
