### ISSUE TITLE
fitbit script doesn't import heartrate

### ISSUE THREAD

**Issue by shrippen** [c99koder/personal-influxdb#6]
As the title says the fitbit script doesn't seem to import my heartrate data - I have used your provided fitbit grafana template and the heartrate panel stays empty. I tried to edit it and look if a typo has made it's way in but couldn't find any problem there. Sadly my python knowledge is not extensive enough to debug myself.

**Comment by c99koder** [comment]
Make sure your application type is set to "Personal" in the Fitbit API console, as heartrate data is restricted to personal use only unless you request special access from them

**Comment by shrippen** [comment]
Yes, that solved the problem. I'm pretty sure that I chose that option when setting up the application but anyway. Thanks for your time.
